/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.31 from the
 * contents of MPQ.xs. Do not edit this file, edit MPQ.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "MPQ.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include <windows.h>
HINSTANCE dll;

typedef char * (__stdcall *Api_GetGtk_Bkn_ptr)(char * );
Api_GetGtk_Bkn_ptr Api_GetGtk_Bkn;
typedef char * (__stdcall *Api_GetBkn32_ptr)(char * );
Api_GetBkn32_ptr Api_GetBkn32;
typedef char * (__stdcall *Api_GetLdw_ptr)(char * );
Api_GetLdw_ptr Api_GetLdw;
typedef char * (__stdcall *Api_GetRunPath_ptr)();
Api_GetRunPath_ptr Api_GetRunPath;
typedef char * (__stdcall *Api_GetOnlineQQlist_ptr)();
Api_GetOnlineQQlist_ptr Api_GetOnlineQQlist;
typedef char * (__stdcall *Api_GetQQlist_ptr)();
Api_GetQQlist_ptr Api_GetQQlist;
typedef char * (__stdcall *Api_GetSessionkey_ptr)(char * );
Api_GetSessionkey_ptr Api_GetSessionkey;
typedef char * (__stdcall *Api_GetClientkey_ptr)(char * );
Api_GetClientkey_ptr Api_GetClientkey;
typedef char * (__stdcall *Api_GetLongClientkey_ptr)(char * );
Api_GetLongClientkey_ptr Api_GetLongClientkey;
typedef char * (__stdcall *Api_GetCookies_ptr)(char * );
Api_GetCookies_ptr Api_GetCookies;
typedef char * (__stdcall *Api_GetPrefix_ptr)();
Api_GetPrefix_ptr Api_GetPrefix;
typedef void (__stdcall *Api_Cache_NameCard_ptr)(char * ,char * ,char * );
Api_Cache_NameCard_ptr Api_Cache_NameCard;
typedef void (__stdcall *Api_DBan_ptr)(char * ,char * );
Api_DBan_ptr Api_DBan;
typedef void (__stdcall *Api_Ban_ptr)(char * ,char * );
Api_Ban_ptr Api_Ban;
typedef bool (__stdcall *Api_Shutup_ptr)(char * ,char * ,char * ,int );
Api_Shutup_ptr Api_Shutup;
typedef bool (__stdcall *Api_IsShutup_ptr)(char *,char *, char *);
Api_IsShutup_ptr Api_IsShutup;
typedef void (__stdcall *Api_SetNotice_ptr)(char * ,char * ,char * ,char * );
Api_SetNotice_ptr Api_SetNotice;
typedef char * (__stdcall *Api_GetNotice_ptr)(char * ,char * );
Api_GetNotice_ptr Api_GetNotice;
typedef char * (__stdcall *Api_GetNameCard_ptr)(char * ,char * ,char * );
Api_GetNameCard_ptr Api_GetNameCard;
typedef void (__stdcall *Api_SetNameCard_ptr)(char * ,char * ,char * ,char * );
Api_SetNameCard_ptr Api_SetNameCard;
typedef void (__stdcall *Api_QuitDG_ptr)(char * ,char * );
Api_QuitDG_ptr Api_QuitDG;
typedef bool (__stdcall *Api_DelFriend_ptr)(char * ,char * );
Api_DelFriend_ptr Api_DelFriend;
typedef bool (__stdcall *Api_Kick_ptr)(char * ,char * ,char * );
Api_Kick_ptr Api_Kick;
typedef void (__stdcall *Api_JoinGroup_ptr)(char * ,char * ,char * );
Api_JoinGroup_ptr Api_JoinGroup;
typedef void (__stdcall *Api_QuitGroup_ptr)(char * ,char * );
Api_QuitGroup_ptr Api_QuitGroup;
typedef char * (__stdcall *Api_UploadPic_ptr)(char * ,int ,char * ,unsigned char * );
Api_UploadPic_ptr Api_UploadPic;
typedef char * (__stdcall *Api_GuidGetPicLink_ptr)(char * );
Api_GuidGetPicLink_ptr Api_GuidGetPicLink;
typedef int (__stdcall *Api_Reply_ptr)(char * ,int ,char * ,char * );
Api_Reply_ptr Api_Reply;
typedef int (__stdcall *Api_SendMsg_ptr)(char * ,int ,int ,char * ,char * ,char * );
Api_SendMsg_ptr Api_SendMsg;
typedef char * (__stdcall *Api_Send_ptr)(char * );
Api_Send_ptr Api_Send;
typedef int (__stdcall *Api_OutPut_ptr)(char * );
Api_OutPut_ptr Api_OutPut;
typedef bool (__stdcall *Api_IsEnable_ptr)();
Api_IsEnable_ptr Api_IsEnable;
typedef bool (__stdcall *Api_Login_ptr)(char * );
Api_Login_ptr Api_Login;
typedef void (__stdcall *Api_Logout_ptr)(char * );
Api_Logout_ptr Api_Logout;
typedef char * (__stdcall *Api_TeaEncrypt_ptr)(char * ,char * );
Api_TeaEncrypt_ptr Api_TeaEncrypt;
typedef char * (__stdcall *Api_TeaDecrypt_ptr)(char * ,char * );
Api_TeaDecrypt_ptr Api_TeaDecrypt;
typedef char * (__stdcall *Api_GetNick_ptr)(char * );
Api_GetNick_ptr Api_GetNick;
typedef char * (__stdcall *Api_GetQQLevel_ptr)(char * );
Api_GetQQLevel_ptr Api_GetQQLevel;
typedef char * (__stdcall *Api_GNGetGid_ptr)(char * );
Api_GNGetGid_ptr Api_GNGetGid;
typedef char * (__stdcall *Api_GidGetGN_ptr)(char * );
Api_GidGetGN_ptr Api_GidGetGN;
typedef int (__stdcall *Api_GetVersion_ptr)();
Api_GetVersion_ptr Api_GetVersion;
typedef char * (__stdcall *Api_GetVersionName_ptr)();
Api_GetVersionName_ptr Api_GetVersionName;
typedef int (__stdcall *Api_GetTimeStamp_ptr)();
Api_GetTimeStamp_ptr Api_GetTimeStamp;
typedef char * (__stdcall *Api_GetLog_ptr)();
Api_GetLog_ptr Api_GetLog;
typedef bool (__stdcall *Api_IfBlock_ptr)(char * );
Api_IfBlock_ptr Api_IfBlock;
typedef char * (__stdcall *Api_GetAdminList_ptr)(char * ,char * );
Api_GetAdminList_ptr Api_GetAdminList;
typedef char * (__stdcall *Api_AddTaotao_ptr)(char * ,char * );
Api_AddTaotao_ptr Api_AddTaotao;
typedef char * (__stdcall *Api_GetSign_ptr)(char * ,char * );
Api_GetSign_ptr Api_GetSign;
typedef char * (__stdcall *Api_SetSign_ptr)(char * ,char * );
Api_SetSign_ptr Api_SetSign;
typedef char * (__stdcall *Api_GetGroupListA_ptr)(char * );
Api_GetGroupListA_ptr Api_GetGroupListA;
typedef char * (__stdcall *Api_GetGroupListB_ptr)(char * );
Api_GetGroupListB_ptr Api_GetGroupListB;
typedef char * (__stdcall *Api_GetGroupMemberA_ptr)(char * ,char * );
Api_GetGroupMemberA_ptr Api_GetGroupMemberA;
typedef char * (__stdcall *Api_GetGroupMemberB_ptr)(char * ,char * );
Api_GetGroupMemberB_ptr Api_GetGroupMemberB;
typedef char * (__stdcall *Api_GetFriendList_ptr)(char * );
Api_GetFriendList_ptr Api_GetFriendList;
typedef int (__stdcall *Api_GetQQAge_ptr)(char * ,char * );
Api_GetQQAge_ptr Api_GetQQAge;
typedef int (__stdcall *Api_GetAge_ptr)(char * ,char * );
Api_GetAge_ptr Api_GetAge;
typedef char * (__stdcall *Api_GetPersonalProfile_ptr)(char * ,char * );
Api_GetPersonalProfile_ptr Api_GetPersonalProfile;
typedef char * (__stdcall *Api_GetEmail_ptr)(char * ,char * );
Api_GetEmail_ptr Api_GetEmail;
typedef int (__stdcall *Api_GetGender_ptr)(char * ,char * );
Api_GetGender_ptr Api_GetGender;
typedef int (__stdcall *Api_SendTyping_ptr)(char * ,char * );
Api_SendTyping_ptr Api_SendTyping;
typedef int (__stdcall *Api_SendShake_ptr)(char * ,char * );
Api_SendShake_ptr Api_SendShake;
typedef char * (__stdcall *Api_GetRadomOnlineQQ_ptr)();
Api_GetRadomOnlineQQ_ptr Api_GetRadomOnlineQQ;
typedef bool (__stdcall *Api_AddQQ_ptr)(char * ,char * ,bool );
Api_AddQQ_ptr Api_AddQQ;
typedef bool (__stdcall *Api_SetOLStatus_ptr)(char * ,int ,char * );
Api_SetOLStatus_ptr Api_SetOLStatus;
typedef char * (__stdcall *Api_GetMC_ptr)();
Api_GetMC_ptr Api_GetMC;
typedef char * (__stdcall *Api_GroupInvitation_ptr)(char * ,char * ,char * );
Api_GroupInvitation_ptr Api_GroupInvitation;
typedef char * (__stdcall *Api_CreateDG_ptr)(char * );
Api_CreateDG_ptr Api_CreateDG;
typedef char * (__stdcall *Api_KickDG_ptr)(char * ,char * ,char * );
Api_KickDG_ptr Api_KickDG;
typedef char * (__stdcall *Api_DGInvitation_ptr)(char * ,char * ,char * );
Api_DGInvitation_ptr Api_DGInvitation;
typedef char * (__stdcall *Api_GetDGList_ptr)(char * );
Api_GetDGList_ptr Api_GetDGList;
typedef bool (__stdcall *Api_SendMusic_ptr)(char * ,int ,char * ,char * ,char * ,char * ,char * ,char * ,char * ,char * ,char * ,char * );
Api_SendMusic_ptr Api_SendMusic;
typedef bool (__stdcall *Api_SendObjectMsg_ptr)(char * ,int ,char * ,char * ,char * ,int );
Api_SendObjectMsg_ptr Api_SendObjectMsg;
typedef bool (__stdcall *Api_IsFriend_ptr)(char *, char *);
Api_IsFriend_ptr Api_IsFriend;
typedef bool (__stdcall *Api_AddFriend_ptr)(char *, char *, char*);
Api_AddFriend_ptr Api_AddFriend;
typedef void (__stdcall *Api_SelfDisable_ptr)();
Api_SelfDisable_ptr Api_SelfDisable;
typedef int (__stdcall *Api_GetClientType_ptr)();
Api_GetClientType_ptr Api_GetClientType;
typedef int (__stdcall *Api_GetClientVer_ptr)();
Api_GetClientVer_ptr Api_GetClientVer;
typedef int (__stdcall *Api_GetPubNo_ptr)();
Api_GetPubNo_ptr Api_GetPubNo;
typedef int (__stdcall *Api_GetMainVer_ptr)();
Api_GetMainVer_ptr Api_GetMainVer;
typedef int (__stdcall *Api_GetTXSSOVer_ptr)();
Api_GetTXSSOVer_ptr Api_GetTXSSOVer;
typedef char * (__stdcall *Api_UploadVoice_ptr)(char *, int);
Api_UploadVoice_ptr Api_UploadVoice;
typedef char * (__stdcall *Api_GuidGetVoiceLink_ptr)(char *, char *);
Api_GuidGetVoiceLink_ptr Api_GuidGetVoiceLink;
typedef char * (__stdcall *Api_AddLogHandler_ptr)(int); //???
Api_AddLogHandler_ptr Api_AddLogHandler;
typedef char * (__stdcall *Api_RemoveLogHandler_ptr)();
Api_RemoveLogHandler_ptr Api_RemoveLogHandler;


#line 187 "MPQ.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 331 "MPQ.c"

XS_EUPXS(XS_MPQ_GetGtk_Bkn); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetGtk_Bkn)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 440 "MPQ.xs"
  RETVAL = Api_GetGtk_Bkn(__arg_0);
#line 346 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetBkn32); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetBkn32)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 448 "MPQ.xs"
  RETVAL = Api_GetBkn32(__arg_0);
#line 366 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetLdw); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetLdw)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 456 "MPQ.xs"
  RETVAL = Api_GetLdw(__arg_0);
#line 386 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetRunPath); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetRunPath)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 463 "MPQ.xs"
  RETVAL = Api_GetRunPath();
#line 404 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetOnlineQQlist); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetOnlineQQlist)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 470 "MPQ.xs"
  RETVAL = Api_GetOnlineQQlist();
#line 422 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetQQlist); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetQQlist)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 477 "MPQ.xs"
  RETVAL = Api_GetQQlist();
#line 440 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetSessionkey); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetSessionkey)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 485 "MPQ.xs"
  RETVAL = Api_GetSessionkey(__arg_0);
#line 460 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetClientkey); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetClientkey)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 493 "MPQ.xs"
  RETVAL = Api_GetClientkey(__arg_0);
#line 480 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetLongClientkey); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetLongClientkey)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 501 "MPQ.xs"
  RETVAL = Api_GetLongClientkey(__arg_0);
#line 500 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetCookies); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetCookies)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 509 "MPQ.xs"
  RETVAL = Api_GetCookies(__arg_0);
#line 520 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetPrefix); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetPrefix)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 516 "MPQ.xs"
  RETVAL = Api_GetPrefix();
#line 538 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_Cache_NameCard); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_Cache_NameCard)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
#line 526 "MPQ.xs"
  Api_Cache_NameCard(__arg_0, __arg_1, __arg_2);
#line 560 "MPQ.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_MPQ_DBan); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_DBan)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
#line 533 "MPQ.xs"
  Api_DBan(__arg_0, __arg_1);
#line 579 "MPQ.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_MPQ_Ban); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_Ban)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
#line 540 "MPQ.xs"
  Api_Ban(__arg_0, __arg_1);
#line 598 "MPQ.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_MPQ_Shutup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_Shutup)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2, __arg_3");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	int	__arg_3 = (int)SvIV(ST(3))
;
	bool	RETVAL;
#line 549 "MPQ.xs"
  RETVAL = Api_Shutup(__arg_0, __arg_1, __arg_2, __arg_3);
#line 622 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_IsShutup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_IsShutup)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	bool	RETVAL;
#line 559 "MPQ.xs"
  RETVAL = Api_IsShutup(__arg_0, __arg_1, __arg_2);
#line 645 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_SetNotice); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_SetNotice)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2, __arg_3");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	char *	__arg_3 = (char *)SvPV_nolen(ST(3))
;
#line 570 "MPQ.xs"
  Api_SetNotice(__arg_0, __arg_1, __arg_2, __arg_3);
#line 669 "MPQ.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_MPQ_GetNotice); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetNotice)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 577 "MPQ.xs"
  RETVAL = Api_GetNotice(__arg_0, __arg_1);
#line 690 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetNameCard); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetNameCard)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	char *	RETVAL;
	dXSTARG;
#line 587 "MPQ.xs"
  RETVAL = Api_GetNameCard(__arg_0, __arg_1, __arg_2);
#line 714 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_SetNameCard); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_SetNameCard)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2, __arg_3");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	char *	__arg_3 = (char *)SvPV_nolen(ST(3))
;
#line 598 "MPQ.xs"
  Api_SetNameCard(__arg_0, __arg_1, __arg_2, __arg_3);
#line 738 "MPQ.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_MPQ_QuitDG); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_QuitDG)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
#line 605 "MPQ.xs"
  Api_QuitDG(__arg_0, __arg_1);
#line 757 "MPQ.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_MPQ_DelFriend); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_DelFriend)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	bool	RETVAL;
#line 612 "MPQ.xs"
  RETVAL = Api_DelFriend(__arg_0, __arg_1);
#line 777 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_Kick); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_Kick)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	bool	RETVAL;
#line 622 "MPQ.xs"
  RETVAL = Api_Kick(__arg_0, __arg_1, __arg_2);
#line 800 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_JoinGroup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_JoinGroup)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
#line 632 "MPQ.xs"
  Api_JoinGroup(__arg_0, __arg_1, __arg_2);
#line 822 "MPQ.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_MPQ_QuitGroup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_QuitGroup)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
#line 639 "MPQ.xs"
  Api_QuitGroup(__arg_0, __arg_1);
#line 841 "MPQ.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_MPQ_UploadPic); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_UploadPic)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2, __arg_3");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	int	__arg_1 = (int)SvIV(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	unsigned char *	__arg_3 = (unsigned char *)SvPV_nolen(ST(3))
;
	char *	RETVAL;
	dXSTARG;
#line 648 "MPQ.xs"
  RETVAL = Api_UploadPic(__arg_0, __arg_1, __arg_2, __arg_3);
#line 866 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GuidGetPicLink); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GuidGetPicLink)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 656 "MPQ.xs"
  RETVAL = Api_GuidGetPicLink(__arg_0);
#line 886 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_Reply); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_Reply)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2, __arg_3");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	int	__arg_1 = (int)SvIV(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	char *	__arg_3 = (char *)SvPV_nolen(ST(3))
;
	int	RETVAL;
	dXSTARG;
#line 667 "MPQ.xs"
  RETVAL = Api_Reply(__arg_0, __arg_1, __arg_2, __arg_3);
#line 912 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_SendMsg); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_SendMsg)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2, __arg_3, __arg_4, __arg_5");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	int	__arg_1 = (int)SvIV(ST(1))
;
	int	__arg_2 = (int)SvIV(ST(2))
;
	char *	__arg_3 = (char *)SvPV_nolen(ST(3))
;
	char *	__arg_4 = (char *)SvPV_nolen(ST(4))
;
	char *	__arg_5 = (char *)SvPV_nolen(ST(5))
;
	int	RETVAL;
	dXSTARG;
#line 680 "MPQ.xs"
  RETVAL = Api_SendMsg(__arg_0, __arg_1, __arg_2, __arg_3, __arg_4, __arg_5);
#line 942 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_Send); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_Send)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 688 "MPQ.xs"
  RETVAL = Api_Send(__arg_0);
#line 962 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_OutPut); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_OutPut)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	int	RETVAL;
	dXSTARG;
#line 696 "MPQ.xs"
  RETVAL = Api_OutPut(__arg_0);
#line 982 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_IsEnable); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_IsEnable)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	bool	RETVAL;
#line 703 "MPQ.xs"
  RETVAL = Api_IsEnable();
#line 999 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_Login); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_Login)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	bool	RETVAL;
#line 711 "MPQ.xs"
  RETVAL = Api_Login(__arg_0);
#line 1018 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_Logout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_Logout)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
#line 719 "MPQ.xs"
  Api_Logout(__arg_0);
#line 1036 "MPQ.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_MPQ_TeaEncrypt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_TeaEncrypt)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 726 "MPQ.xs"
  RETVAL = Api_TeaEncrypt(__arg_0, __arg_1);
#line 1057 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_TeaDecrypt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_TeaDecrypt)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 735 "MPQ.xs"
  RETVAL = Api_TeaDecrypt(__arg_0, __arg_1);
#line 1079 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetNick); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetNick)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 743 "MPQ.xs"
  RETVAL = Api_GetNick(__arg_0);
#line 1099 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetQQLevel); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetQQLevel)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 751 "MPQ.xs"
  RETVAL = Api_GetQQLevel(__arg_0);
#line 1119 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GNGetGid); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GNGetGid)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 759 "MPQ.xs"
  RETVAL = Api_GNGetGid(__arg_0);
#line 1139 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GidGetGN); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GidGetGN)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 767 "MPQ.xs"
  RETVAL = Api_GidGetGN(__arg_0);
#line 1159 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetVersion); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetVersion)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 774 "MPQ.xs"
  RETVAL = Api_GetVersion();
#line 1177 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetVersionName); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetVersionName)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 781 "MPQ.xs"
  RETVAL = Api_GetVersionName();
#line 1195 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetTimeStamp); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetTimeStamp)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 788 "MPQ.xs"
  RETVAL = Api_GetTimeStamp();
#line 1213 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetLog); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetLog)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 795 "MPQ.xs"
  RETVAL = Api_GetLog();
#line 1231 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_IfBlock); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_IfBlock)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	bool	RETVAL;
#line 803 "MPQ.xs"
  RETVAL = Api_IfBlock(__arg_0);
#line 1250 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetAdminList); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetAdminList)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 812 "MPQ.xs"
  RETVAL = Api_GetAdminList(__arg_0, __arg_1);
#line 1272 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_AddTaotao); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_AddTaotao)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 821 "MPQ.xs"
  RETVAL = Api_AddTaotao(__arg_0, __arg_1);
#line 1294 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetSign); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetSign)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 830 "MPQ.xs"
  RETVAL = Api_GetSign(__arg_0, __arg_1);
#line 1316 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_SetSign); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_SetSign)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 839 "MPQ.xs"
  RETVAL = Api_SetSign(__arg_0, __arg_1);
#line 1338 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetGroupListA); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetGroupListA)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 847 "MPQ.xs"
  RETVAL = Api_GetGroupListA(__arg_0);
#line 1358 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetGroupListB); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetGroupListB)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 855 "MPQ.xs"
  RETVAL = Api_GetGroupListB(__arg_0);
#line 1378 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetGroupMemberA); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetGroupMemberA)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 864 "MPQ.xs"
  RETVAL = Api_GetGroupMemberA(__arg_0, __arg_1);
#line 1400 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetGroupMemberB); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetGroupMemberB)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 873 "MPQ.xs"
  RETVAL = Api_GetGroupMemberB(__arg_0, __arg_1);
#line 1422 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetFriendList); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetFriendList)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 881 "MPQ.xs"
  RETVAL = Api_GetFriendList(__arg_0);
#line 1442 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetQQAge); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetQQAge)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	int	RETVAL;
	dXSTARG;
#line 890 "MPQ.xs"
  RETVAL = Api_GetQQAge(__arg_0, __arg_1);
#line 1464 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetAge); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetAge)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	int	RETVAL;
	dXSTARG;
#line 899 "MPQ.xs"
  RETVAL = Api_GetAge(__arg_0, __arg_1);
#line 1486 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetPersonalProfile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetPersonalProfile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 908 "MPQ.xs"
  RETVAL = Api_GetPersonalProfile(__arg_0, __arg_1);
#line 1508 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetEmail); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetEmail)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 917 "MPQ.xs"
  RETVAL = Api_GetEmail(__arg_0, __arg_1);
#line 1530 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetGender); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetGender)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	int	RETVAL;
	dXSTARG;
#line 926 "MPQ.xs"
  RETVAL = Api_GetGender(__arg_0, __arg_1);
#line 1552 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_SendTyping); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_SendTyping)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	int	RETVAL;
	dXSTARG;
#line 935 "MPQ.xs"
  RETVAL = Api_SendTyping(__arg_0, __arg_1);
#line 1574 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_SendShake); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_SendShake)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	int	RETVAL;
	dXSTARG;
#line 944 "MPQ.xs"
  RETVAL = Api_SendShake(__arg_0, __arg_1);
#line 1596 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetRadomOnlineQQ); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetRadomOnlineQQ)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 951 "MPQ.xs"
  RETVAL = Api_GetRadomOnlineQQ();
#line 1614 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_AddQQ); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_AddQQ)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	bool	__arg_2 = (bool)SvTRUE(ST(2))
;
	bool	RETVAL;
#line 961 "MPQ.xs"
  RETVAL = Api_AddQQ(__arg_0, __arg_1, __arg_2);
#line 1637 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_SetOLStatus); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_SetOLStatus)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	int	__arg_1 = (int)SvIV(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	bool	RETVAL;
#line 971 "MPQ.xs"
  RETVAL = Api_SetOLStatus(__arg_0, __arg_1, __arg_2);
#line 1660 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetMC); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetMC)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 978 "MPQ.xs"
  RETVAL = Api_GetMC();
#line 1678 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GroupInvitation); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GroupInvitation)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	char *	RETVAL;
	dXSTARG;
#line 988 "MPQ.xs"
  RETVAL = Api_GroupInvitation(__arg_0, __arg_1, __arg_2);
#line 1702 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_CreateDG); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_CreateDG)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 996 "MPQ.xs"
  RETVAL = Api_CreateDG(__arg_0);
#line 1722 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_KickDG); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_KickDG)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	char *	RETVAL;
	dXSTARG;
#line 1006 "MPQ.xs"
  RETVAL = Api_KickDG(__arg_0, __arg_1, __arg_2);
#line 1746 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_DGInvitation); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_DGInvitation)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	char *	RETVAL;
	dXSTARG;
#line 1016 "MPQ.xs"
  RETVAL = Api_DGInvitation(__arg_0, __arg_1, __arg_2);
#line 1770 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetDGList); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetDGList)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 1024 "MPQ.xs"
  RETVAL = Api_GetDGList(__arg_0);
#line 1790 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_SendMusic); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_SendMusic)
{
    dVAR; dXSARGS;
    if (items != 12)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2, __arg_3, __arg_4, __arg_5, __arg_6, __arg_7, __arg_8, __arg_9, __arg_10, __arg_11");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	int	__arg_1 = (int)SvIV(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	char *	__arg_3 = (char *)SvPV_nolen(ST(3))
;
	char *	__arg_4 = (char *)SvPV_nolen(ST(4))
;
	char *	__arg_5 = (char *)SvPV_nolen(ST(5))
;
	char *	__arg_6 = (char *)SvPV_nolen(ST(6))
;
	char *	__arg_7 = (char *)SvPV_nolen(ST(7))
;
	char *	__arg_8 = (char *)SvPV_nolen(ST(8))
;
	char *	__arg_9 = (char *)SvPV_nolen(ST(9))
;
	char *	__arg_10 = (char *)SvPV_nolen(ST(10))
;
	char *	__arg_11 = (char *)SvPV_nolen(ST(11))
;
	bool	RETVAL;
#line 1043 "MPQ.xs"
  RETVAL = Api_SendMusic(__arg_0, __arg_1, __arg_2, __arg_3, __arg_4, __arg_5, __arg_6, __arg_7, __arg_8, __arg_9, __arg_10, __arg_11);
#line 1831 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_SendObjectMsg); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_SendObjectMsg)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2, __arg_3, __arg_4, __arg_5");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	int	__arg_1 = (int)SvIV(ST(1))
;
	char *	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	char *	__arg_3 = (char *)SvPV_nolen(ST(3))
;
	char *	__arg_4 = (char *)SvPV_nolen(ST(4))
;
	int	__arg_5 = (int)SvIV(ST(5))
;
	bool	RETVAL;
#line 1056 "MPQ.xs"
  RETVAL = Api_SendObjectMsg(__arg_0, __arg_1, __arg_2, __arg_3, __arg_4, __arg_5);
#line 1860 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_IsFriend); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_IsFriend)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	bool	RETVAL;
#line 1065 "MPQ.xs"
  RETVAL = Api_IsFriend(__arg_0, __arg_1);
#line 1881 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_AddFriend); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_AddFriend)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "__arg_0, __arg_1, __arg_2");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char*	__arg_2 = (char *)SvPV_nolen(ST(2))
;
	bool	RETVAL;
#line 1075 "MPQ.xs"
  RETVAL = Api_AddFriend(__arg_0, __arg_1, __arg_2);
#line 1904 "MPQ.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_SelfDisable); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_SelfDisable)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 1082 "MPQ.xs"
  Api_SelfDisable();
#line 1920 "MPQ.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_MPQ_GetClientType); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetClientType)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 1087 "MPQ.xs"
  RETVAL = Api_GetClientType();
#line 1937 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetClientVer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetClientVer)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 1094 "MPQ.xs"
  RETVAL = Api_GetClientVer();
#line 1955 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetPubNo); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetPubNo)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 1101 "MPQ.xs"
  RETVAL = Api_GetPubNo();
#line 1973 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetMainVer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetMainVer)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 1108 "MPQ.xs"
  RETVAL = Api_GetMainVer();
#line 1991 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GetTXSSOVer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GetTXSSOVer)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 1115 "MPQ.xs"
  RETVAL = Api_GetTXSSOVer();
#line 2009 "MPQ.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_UploadVoice); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_UploadVoice)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	int	__arg_1 = (int)SvIV(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 1124 "MPQ.xs"
  RETVAL = Api_UploadVoice(__arg_0, __arg_1);
#line 2031 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_GuidGetVoiceLink); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_GuidGetVoiceLink)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "__arg_0, __arg_1");
    {
	char *	__arg_0 = (char *)SvPV_nolen(ST(0))
;
	char *	__arg_1 = (char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 1133 "MPQ.xs"
  RETVAL = Api_GuidGetVoiceLink(__arg_0, __arg_1);
#line 2053 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_AddLogHandler); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_AddLogHandler)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "__arg_0");
    {
	int	__arg_0 = (int)SvIV(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 1141 "MPQ.xs"
  RETVAL = Api_AddLogHandler(__arg_0);
#line 2073 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_MPQ_RemoveLogHandler); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MPQ_RemoveLogHandler)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 1148 "MPQ.xs"
  RETVAL = Api_RemoveLogHandler();
#line 2091 "MPQ.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_MPQ); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_MPQ)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("MPQ::GetGtk_Bkn", XS_MPQ_GetGtk_Bkn);
        newXS_deffile("MPQ::GetBkn32", XS_MPQ_GetBkn32);
        newXS_deffile("MPQ::GetLdw", XS_MPQ_GetLdw);
        newXS_deffile("MPQ::GetRunPath", XS_MPQ_GetRunPath);
        newXS_deffile("MPQ::GetOnlineQQlist", XS_MPQ_GetOnlineQQlist);
        newXS_deffile("MPQ::GetQQlist", XS_MPQ_GetQQlist);
        newXS_deffile("MPQ::GetSessionkey", XS_MPQ_GetSessionkey);
        newXS_deffile("MPQ::GetClientkey", XS_MPQ_GetClientkey);
        newXS_deffile("MPQ::GetLongClientkey", XS_MPQ_GetLongClientkey);
        newXS_deffile("MPQ::GetCookies", XS_MPQ_GetCookies);
        newXS_deffile("MPQ::GetPrefix", XS_MPQ_GetPrefix);
        newXS_deffile("MPQ::Cache_NameCard", XS_MPQ_Cache_NameCard);
        newXS_deffile("MPQ::DBan", XS_MPQ_DBan);
        newXS_deffile("MPQ::Ban", XS_MPQ_Ban);
        newXS_deffile("MPQ::Shutup", XS_MPQ_Shutup);
        newXS_deffile("MPQ::IsShutup", XS_MPQ_IsShutup);
        newXS_deffile("MPQ::SetNotice", XS_MPQ_SetNotice);
        newXS_deffile("MPQ::GetNotice", XS_MPQ_GetNotice);
        newXS_deffile("MPQ::GetNameCard", XS_MPQ_GetNameCard);
        newXS_deffile("MPQ::SetNameCard", XS_MPQ_SetNameCard);
        newXS_deffile("MPQ::QuitDG", XS_MPQ_QuitDG);
        newXS_deffile("MPQ::DelFriend", XS_MPQ_DelFriend);
        newXS_deffile("MPQ::Kick", XS_MPQ_Kick);
        newXS_deffile("MPQ::JoinGroup", XS_MPQ_JoinGroup);
        newXS_deffile("MPQ::QuitGroup", XS_MPQ_QuitGroup);
        newXS_deffile("MPQ::UploadPic", XS_MPQ_UploadPic);
        newXS_deffile("MPQ::GuidGetPicLink", XS_MPQ_GuidGetPicLink);
        newXS_deffile("MPQ::Reply", XS_MPQ_Reply);
        newXS_deffile("MPQ::SendMsg", XS_MPQ_SendMsg);
        newXS_deffile("MPQ::Send", XS_MPQ_Send);
        newXS_deffile("MPQ::OutPut", XS_MPQ_OutPut);
        newXS_deffile("MPQ::IsEnable", XS_MPQ_IsEnable);
        newXS_deffile("MPQ::Login", XS_MPQ_Login);
        newXS_deffile("MPQ::Logout", XS_MPQ_Logout);
        newXS_deffile("MPQ::TeaEncrypt", XS_MPQ_TeaEncrypt);
        newXS_deffile("MPQ::TeaDecrypt", XS_MPQ_TeaDecrypt);
        newXS_deffile("MPQ::GetNick", XS_MPQ_GetNick);
        newXS_deffile("MPQ::GetQQLevel", XS_MPQ_GetQQLevel);
        newXS_deffile("MPQ::GNGetGid", XS_MPQ_GNGetGid);
        newXS_deffile("MPQ::GidGetGN", XS_MPQ_GidGetGN);
        newXS_deffile("MPQ::GetVersion", XS_MPQ_GetVersion);
        newXS_deffile("MPQ::GetVersionName", XS_MPQ_GetVersionName);
        newXS_deffile("MPQ::GetTimeStamp", XS_MPQ_GetTimeStamp);
        newXS_deffile("MPQ::GetLog", XS_MPQ_GetLog);
        newXS_deffile("MPQ::IfBlock", XS_MPQ_IfBlock);
        newXS_deffile("MPQ::GetAdminList", XS_MPQ_GetAdminList);
        newXS_deffile("MPQ::AddTaotao", XS_MPQ_AddTaotao);
        newXS_deffile("MPQ::GetSign", XS_MPQ_GetSign);
        newXS_deffile("MPQ::SetSign", XS_MPQ_SetSign);
        newXS_deffile("MPQ::GetGroupListA", XS_MPQ_GetGroupListA);
        newXS_deffile("MPQ::GetGroupListB", XS_MPQ_GetGroupListB);
        newXS_deffile("MPQ::GetGroupMemberA", XS_MPQ_GetGroupMemberA);
        newXS_deffile("MPQ::GetGroupMemberB", XS_MPQ_GetGroupMemberB);
        newXS_deffile("MPQ::GetFriendList", XS_MPQ_GetFriendList);
        newXS_deffile("MPQ::GetQQAge", XS_MPQ_GetQQAge);
        newXS_deffile("MPQ::GetAge", XS_MPQ_GetAge);
        newXS_deffile("MPQ::GetPersonalProfile", XS_MPQ_GetPersonalProfile);
        newXS_deffile("MPQ::GetEmail", XS_MPQ_GetEmail);
        newXS_deffile("MPQ::GetGender", XS_MPQ_GetGender);
        newXS_deffile("MPQ::SendTyping", XS_MPQ_SendTyping);
        newXS_deffile("MPQ::SendShake", XS_MPQ_SendShake);
        newXS_deffile("MPQ::GetRadomOnlineQQ", XS_MPQ_GetRadomOnlineQQ);
        newXS_deffile("MPQ::AddQQ", XS_MPQ_AddQQ);
        newXS_deffile("MPQ::SetOLStatus", XS_MPQ_SetOLStatus);
        newXS_deffile("MPQ::GetMC", XS_MPQ_GetMC);
        newXS_deffile("MPQ::GroupInvitation", XS_MPQ_GroupInvitation);
        newXS_deffile("MPQ::CreateDG", XS_MPQ_CreateDG);
        newXS_deffile("MPQ::KickDG", XS_MPQ_KickDG);
        newXS_deffile("MPQ::DGInvitation", XS_MPQ_DGInvitation);
        newXS_deffile("MPQ::GetDGList", XS_MPQ_GetDGList);
        newXS_deffile("MPQ::SendMusic", XS_MPQ_SendMusic);
        newXS_deffile("MPQ::SendObjectMsg", XS_MPQ_SendObjectMsg);
        newXS_deffile("MPQ::IsFriend", XS_MPQ_IsFriend);
        newXS_deffile("MPQ::AddFriend", XS_MPQ_AddFriend);
        newXS_deffile("MPQ::SelfDisable", XS_MPQ_SelfDisable);
        newXS_deffile("MPQ::GetClientType", XS_MPQ_GetClientType);
        newXS_deffile("MPQ::GetClientVer", XS_MPQ_GetClientVer);
        newXS_deffile("MPQ::GetPubNo", XS_MPQ_GetPubNo);
        newXS_deffile("MPQ::GetMainVer", XS_MPQ_GetMainVer);
        newXS_deffile("MPQ::GetTXSSOVer", XS_MPQ_GetTXSSOVer);
        newXS_deffile("MPQ::UploadVoice", XS_MPQ_UploadVoice);
        newXS_deffile("MPQ::GuidGetVoiceLink", XS_MPQ_GuidGetVoiceLink);
        newXS_deffile("MPQ::AddLogHandler", XS_MPQ_AddLogHandler);
        newXS_deffile("MPQ::RemoveLogHandler", XS_MPQ_RemoveLogHandler);

    /* Initialisation Section */

#line 180 "MPQ.xs"
  if (! (dll = LoadLibrary("Message.dll"))) {
    croak("cannot load dll.");
  }
if (! (Api_GetGtk_Bkn = (Api_GetGtk_Bkn_ptr)GetProcAddress(dll, "Api_GetGtk_Bkn"))) {
  croak("cannot load Api_GetGtk_Bkn");
}
if (! (Api_GetBkn32 = (Api_GetBkn32_ptr)GetProcAddress(dll, "Api_GetBkn32"))) {
  croak("cannot load Api_GetBkn32");
}
if (! (Api_GetLdw = (Api_GetLdw_ptr)GetProcAddress(dll, "Api_GetLdw"))) {
  croak("cannot load Api_GetLdw");
}
if (! (Api_GetRunPath = (Api_GetRunPath_ptr)GetProcAddress(dll, "Api_GetRunPath"))) {
  croak("cannot load Api_GetRunPath");
}
if (! (Api_GetOnlineQQlist = (Api_GetOnlineQQlist_ptr)GetProcAddress(dll, "Api_GetOnlineQQlist"))) {
  croak("cannot load Api_GetOnlineQQlist");
}
if (! (Api_GetQQlist = (Api_GetQQlist_ptr)GetProcAddress(dll, "Api_GetQQlist"))) {
  croak("cannot load Api_GetQQlist");
}
if (! (Api_GetSessionkey = (Api_GetSessionkey_ptr)GetProcAddress(dll, "Api_GetSessionkey"))) {
  croak("cannot load Api_GetSessionkey");
}
if (! (Api_GetClientkey = (Api_GetClientkey_ptr)GetProcAddress(dll, "Api_GetClientkey"))) {
  croak("cannot load Api_GetClientkey");
}
if (! (Api_GetLongClientkey = (Api_GetLongClientkey_ptr)GetProcAddress(dll, "Api_GetLongClientkey"))) {
  croak("cannot load Api_GetLongClientkey");
}
if (! (Api_GetCookies = (Api_GetCookies_ptr)GetProcAddress(dll, "Api_GetCookies"))) {
  croak("cannot load Api_GetCookies");
}
if (! (Api_GetPrefix = (Api_GetPrefix_ptr)GetProcAddress(dll, "Api_GetPrefix"))) {
  croak("cannot load Api_GetPrefix");
}
if (! (Api_Cache_NameCard = (Api_Cache_NameCard_ptr)GetProcAddress(dll, "Api_Cache_NameCard"))) {
  croak("cannot load Api_Cache_NameCard");
}
if (! (Api_DBan = (Api_DBan_ptr)GetProcAddress(dll, "Api_DBan"))) {
  croak("cannot load Api_DBan");
}
if (! (Api_Ban = (Api_Ban_ptr)GetProcAddress(dll, "Api_Ban"))) {
  croak("cannot load Api_Ban");
}
if (! (Api_Shutup = (Api_Shutup_ptr)GetProcAddress(dll, "Api_Shutup"))) {
  croak("cannot load Api_Shutup");
}
if (! (Api_IsShutup = (Api_IsShutup_ptr)GetProcAddress(dll, "Api_IsShutup"))) {
  croak("cannot load Api_IsShutup");
}
if (! (Api_SetNotice = (Api_SetNotice_ptr)GetProcAddress(dll, "Api_SetNotice"))) {
  croak("cannot load Api_SetNotice");
}
if (! (Api_GetNotice = (Api_GetNotice_ptr)GetProcAddress(dll, "Api_GetNotice"))) {
  croak("cannot load Api_GetNotice");
}
if (! (Api_GetNameCard = (Api_GetNameCard_ptr)GetProcAddress(dll, "Api_GetNameCard"))) {
  croak("cannot load Api_GetNameCard");
}
if (! (Api_SetNameCard = (Api_SetNameCard_ptr)GetProcAddress(dll, "Api_SetNameCard"))) {
  croak("cannot load Api_SetNameCard");
}
if (! (Api_QuitDG = (Api_QuitDG_ptr)GetProcAddress(dll, "Api_QuitDG"))) {
  croak("cannot load Api_QuitDG");
}
if (! (Api_DelFriend = (Api_DelFriend_ptr)GetProcAddress(dll, "Api_DelFriend"))) {
  croak("cannot load Api_DelFriend");
}
if (! (Api_Kick = (Api_Kick_ptr)GetProcAddress(dll, "Api_Kick"))) {
  croak("cannot load Api_Kick");
}
if (! (Api_JoinGroup = (Api_JoinGroup_ptr)GetProcAddress(dll, "Api_JoinGroup"))) {
  croak("cannot load Api_JoinGroup");
}
if (! (Api_QuitGroup = (Api_QuitGroup_ptr)GetProcAddress(dll, "Api_QuitGroup"))) {
  croak("cannot load Api_QuitGroup");
}
if (! (Api_UploadPic = (Api_UploadPic_ptr)GetProcAddress(dll, "Api_UploadPic"))) {
  croak("cannot load Api_UploadPic");
}
if (! (Api_GuidGetPicLink = (Api_GuidGetPicLink_ptr)GetProcAddress(dll, "Api_GuidGetPicLink"))) {
  croak("cannot load Api_GuidGetPicLink");
}
if (! (Api_Reply = (Api_Reply_ptr)GetProcAddress(dll, "Api_Reply"))) {
  croak("cannot load Api_Reply");
}
if (! (Api_SendMsg = (Api_SendMsg_ptr)GetProcAddress(dll, "Api_SendMsg"))) {
  croak("cannot load Api_SendMsg");
}
if (! (Api_Send = (Api_Send_ptr)GetProcAddress(dll, "Api_Send"))) {
  croak("cannot load Api_Send");
}
if (! (Api_OutPut = (Api_OutPut_ptr)GetProcAddress(dll, "Api_OutPut"))) {
  croak("cannot load Api_OutPut");
}
if (! (Api_IsEnable = (Api_IsEnable_ptr)GetProcAddress(dll, "Api_IsEnable"))) {
  croak("cannot load Api_IsEnable");
}
if (! (Api_Login = (Api_Login_ptr)GetProcAddress(dll, "Api_Login"))) {
  croak("cannot load Api_Login");
}
if (! (Api_Logout = (Api_Logout_ptr)GetProcAddress(dll, "Api_Logout"))) {
  croak("cannot load Api_Logout");
}
if (! (Api_TeaEncrypt = (Api_TeaEncrypt_ptr)GetProcAddress(dll, "Api_Tea¼ÓÃÜ"))) {
  croak("cannot load Api_TeaEncrypt");
}
if (! (Api_TeaDecrypt = (Api_TeaDecrypt_ptr)GetProcAddress(dll, "Api_Tea½âÃÜ"))) {
  croak("cannot load Api_TeaDecrypt");
}
if (! (Api_GetNick = (Api_GetNick_ptr)GetProcAddress(dll, "Api_GetNick"))) {
  croak("cannot load Api_GetNick");
}
if (! (Api_GetQQLevel = (Api_GetQQLevel_ptr)GetProcAddress(dll, "Api_GetQQLevel"))) {
  croak("cannot load Api_GetQQLevel");
}
if (! (Api_GNGetGid = (Api_GNGetGid_ptr)GetProcAddress(dll, "Api_GNGetGid"))) {
  croak("cannot load Api_GNGetGid");
}
if (! (Api_GidGetGN = (Api_GidGetGN_ptr)GetProcAddress(dll, "Api_GidGetGN"))) {
  croak("cannot load Api_GidGetGN");
}
if (! (Api_GetVersion = (Api_GetVersion_ptr)GetProcAddress(dll, "Api_GetVersion"))) {
  croak("cannot load Api_GetVersion");
}
if (! (Api_GetVersionName = (Api_GetVersionName_ptr)GetProcAddress(dll, "Api_GetVersionName"))) {
  croak("cannot load Api_GetVersionName");
}
if (! (Api_GetTimeStamp = (Api_GetTimeStamp_ptr)GetProcAddress(dll, "Api_GetTimeStamp"))) {
  croak("cannot load Api_GetTimeStamp");
}
if (! (Api_GetLog = (Api_GetLog_ptr)GetProcAddress(dll, "Api_GetLog"))) {
  croak("cannot load Api_GetLog");
}
if (! (Api_IfBlock = (Api_IfBlock_ptr)GetProcAddress(dll, "Api_IfBlock"))) {
  croak("cannot load Api_IfBlock");
}
if (! (Api_GetAdminList = (Api_GetAdminList_ptr)GetProcAddress(dll, "Api_GetAdminList"))) {
  croak("cannot load Api_GetAdminList");
}
if (! (Api_AddTaotao = (Api_AddTaotao_ptr)GetProcAddress(dll, "Api_AddTaotao"))) {
  croak("cannot load Api_AddTaotao");
}
if (! (Api_GetSign = (Api_GetSign_ptr)GetProcAddress(dll, "Api_GetSign"))) {
  croak("cannot load Api_GetSign");
}
if (! (Api_SetSign = (Api_SetSign_ptr)GetProcAddress(dll, "Api_SetSign"))) {
  croak("cannot load Api_SetSign");
}
if (! (Api_GetGroupListA = (Api_GetGroupListA_ptr)GetProcAddress(dll, "Api_GetGroupListA"))) {
  croak("cannot load Api_GetGroupListA");
}
if (! (Api_GetGroupListB = (Api_GetGroupListB_ptr)GetProcAddress(dll, "Api_GetGroupListB"))) {
  croak("cannot load Api_GetGroupListB");
}
if (! (Api_GetGroupMemberA = (Api_GetGroupMemberA_ptr)GetProcAddress(dll, "Api_GetGroupMemberA"))) {
  croak("cannot load Api_GetGroupMemberA");
}
if (! (Api_GetGroupMemberB = (Api_GetGroupMemberB_ptr)GetProcAddress(dll, "Api_GetGroupMemberB"))) {
  croak("cannot load Api_GetGroupMemberB");
}
if (! (Api_GetFriendList = (Api_GetFriendList_ptr)GetProcAddress(dll, "Api_GetFriendList"))) {
  croak("cannot load Api_GetFriendList");
}
if (! (Api_GetQQAge = (Api_GetQQAge_ptr)GetProcAddress(dll, "Api_GetQQAge"))) {
  croak("cannot load Api_GetQQAge");
}
if (! (Api_GetAge = (Api_GetAge_ptr)GetProcAddress(dll, "Api_GetAge"))) {
  croak("cannot load Api_GetAge");
}
if (! (Api_GetPersonalProfile = (Api_GetPersonalProfile_ptr)GetProcAddress(dll, "Api_GetPersonalProfile"))) {
  croak("cannot load Api_GetPersonalProfile");
}
if (! (Api_GetEmail = (Api_GetEmail_ptr)GetProcAddress(dll, "Api_GetEmail"))) {
  croak("cannot load Api_GetEmail");
}
if (! (Api_GetGender = (Api_GetGender_ptr)GetProcAddress(dll, "Api_GetGender"))) {
  croak("cannot load Api_GetGender");
}
if (! (Api_SendTyping = (Api_SendTyping_ptr)GetProcAddress(dll, "Api_SendTyping"))) {
  croak("cannot load Api_SendTyping");
}
if (! (Api_SendShake = (Api_SendShake_ptr)GetProcAddress(dll, "Api_SendShake"))) {
  croak("cannot load Api_SendShake");
}
if (! (Api_GetRadomOnlineQQ = (Api_GetRadomOnlineQQ_ptr)GetProcAddress(dll, "Api_GetRadomOnlineQQ"))) {
  croak("cannot load Api_GetRadomOnlineQQ");
}
if (! (Api_AddQQ = (Api_AddQQ_ptr)GetProcAddress(dll, "Api_AddQQ"))) {
  croak("cannot load Api_AddQQ");
}
if (! (Api_SetOLStatus = (Api_SetOLStatus_ptr)GetProcAddress(dll, "Api_SetOLStatus"))) {
  croak("cannot load Api_SetOLStatus");
}
if (! (Api_GetMC = (Api_GetMC_ptr)GetProcAddress(dll, "Api_GetMC"))) {
  croak("cannot load Api_GetMC");
}
if (! (Api_GroupInvitation = (Api_GroupInvitation_ptr)GetProcAddress(dll, "Api_GroupInvitation"))) {
  croak("cannot load Api_GroupInvitation");
}
if (! (Api_CreateDG = (Api_CreateDG_ptr)GetProcAddress(dll, "Api_CreateDG"))) {
  croak("cannot load Api_CreateDG");
}
if (! (Api_KickDG = (Api_KickDG_ptr)GetProcAddress(dll, "Api_KickDG"))) {
  croak("cannot load Api_KickDG");
}
if (! (Api_DGInvitation = (Api_DGInvitation_ptr)GetProcAddress(dll, "Api_DGInvitation"))) {
  croak("cannot load Api_DGInvitation");
}
if (! (Api_GetDGList = (Api_GetDGList_ptr)GetProcAddress(dll, "Api_GetDGList"))) {
  croak("cannot load Api_GetDGList");
}
if (! (Api_SendMusic = (Api_SendMusic_ptr)GetProcAddress(dll, "Api_SendMusic"))) {
  croak("cannot load Api_SendMusic");
}
if (! (Api_SendObjectMsg = (Api_SendObjectMsg_ptr)GetProcAddress(dll, "Api_SendObjectMsg"))) {
  croak("cannot load Api_SendObjectMsg");
}
if (! (Api_IsFriend = (Api_IsFriend_ptr)GetProcAddress(dll, "Api_IsFriend"))) {
  croak("cannot load Api_IsFriend");
}
if (! (Api_AddFriend = (Api_AddFriend_ptr)GetProcAddress(dll, "Api_AddFriend"))) {
  croak("cannot load Api_AddFriend");
}
if (! (Api_SelfDisable = (Api_SelfDisable_ptr)GetProcAddress(dll, "Api_SelfDisable"))) {
  croak("cannot load Api_SelfDisable");
}
if (! (Api_GetClientType = (Api_GetClientType_ptr)GetProcAddress(dll, "Api_GetClientType"))) {
  croak("cannot load Api_GetClientType");
}
if (! (Api_GetClientVer = (Api_GetClientVer_ptr)GetProcAddress(dll, "Api_GetClientVer"))) {
  croak("cannot load Api_GetClientVer");
}
if (! (Api_GetPubNo = (Api_GetPubNo_ptr)GetProcAddress(dll, "Api_GetPubNo"))) {
  croak("cannot load Api_GetPubNo");
}
if (! (Api_GetMainVer = (Api_GetMainVer_ptr)GetProcAddress(dll, "Api_GetMainVer"))) {
  croak("cannot load Api_GetMainVer");
}
if (! (Api_GetTXSSOVer = (Api_GetTXSSOVer_ptr)GetProcAddress(dll, "Api_GetTXSSOVer"))) {
  croak("cannot load Api_GetTXSSOVer");
}
if (! (Api_UploadVoice = (Api_UploadVoice_ptr)GetProcAddress(dll, "Api_UploadVoice"))) {
  croak("cannot load Api_UploadVoice");
}
if (! (Api_GuidGetVoiceLink = (Api_GuidGetVoiceLink_ptr)GetProcAddress(dll, "Api_GuidGetVoiceLink"))) {
  croak("cannot load Api_GuidGetVoiceLink");
}
if (! (Api_AddLogHandler = (Api_AddLogHandler_ptr)GetProcAddress(dll, "Api_AddLogHandler"))) {
  croak("cannot load Api_AddLogHandler");
}
if (! (Api_RemoveLogHandler = (Api_RemoveLogHandler_ptr)GetProcAddress(dll, "Api_RemoveLogHandler"))) {
  croak("cannot load Api_RemoveLogHandler");
}

#line 2469 "MPQ.c"

    /* End of Initialisation Section */

#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

