# ~/.xinitrc

# Jump to X11 env

#eval "$(dbus-launch --sh-syntax --exit-with-session)"

export LANG=zh_CN.UTF-8 TERM=xterm LC_ALL= XIM=fcitx XIM_PROGRAM=fcitx
export LC_CTYPE=zh_CN.UTF-8
export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE=fcitx GTK_IM_MODULE=fcitx
export PATH="$HOME/Apps/bin:$PATH"
xrdb ~/.Xresource
#exec /usr/bin/fvwm
#exec ck-launch-session /usr/bin/fvwm
#export KDEWM=fvwm
exec /usr/bin/startkde
#exec /usr/bin/mate-session
