#!/bin/zsh
setopt AUTO_LIST
setopt AUTO_MENU
#开启此选项，补全时会直接选中菜单项
#setopt MENU_COMPLETE

# completion fpath
fpath+=("$HOME/.zsh/completions")
autoload -Uz compinit
compinit

#自动补全缓存
#zstyle ':completion::complete:*' use-cache on
#zstyle ':completion::complete:*' cache-path .zcache
#zstyle ':completion:*:cd:*' ignore-parents parent pwd

#自动补全选项
zstyle ':completion:*' verbose yes
zstyle ':completion:*' menu select
zstyle ':completion:*:*:default' force-list always
zstyle ':completion:*' select-prompt '%SSelect:  lines: %L  matches: %M  [%p]'

zstyle ':completion:*:match:*' original only
zstyle ':completion::prefix-1:*' completer _complete
zstyle ':completion:predict:*' completer _complete
zstyle ':completion:incremental:*' completer _complete _correct
zstyle ':completion:*' completer _complete _prefix _correct _prefix _match _approximate

#路径补全
zstyle ':completion:*' expand 'yes'
zstyle ':completion:*' squeeze-shlashes 'yes'
zstyle ':completion::complete:*' '\\'

#彩色补全菜单 
export ZLSCOLORS="${LS_COLORS}"
zmodload zsh/complist
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

#修正大小写
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
#错误校正      
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

#kill 命令补全      
compdef pkill=kill
compdef pkill=killall
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:*:*:*:processes' force-list always
zstyle ':completion:*:processes' command 'ps -au$USER'

#补全类型提示分组 
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*' group-name ''
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:descriptions' format $'\e[01;33m -- %d --\e[0m'
zstyle ':completion:*:messages' format $'\e[01;35m -- %d --\e[0m'
zstyle ':completion:*:warnings' format $'\e[01;31m -- No Matches Found --\e[0m'
zstyle ':completion:*:corrections' format $'\e[01;32m -- %d (errors: %e) --\e[0m'

# cd ~ 补全顺序
zstyle ':completion:*:-tilde-:*' group-order 'named-directories' 'path-directories' 'users' 'expand'

#补全 ping
zstyle ':completion:*:ping:*' hosts 192.168.128.1{38,} g.cn \
       192.168.{1,0}.1{{7..9},}

#补全 ssh scp sftp 等
my_accounts=(
{tusooa,root}@{192.168.1.1,192.168.0.1}
)
zstyle ':completion:*:my-accounts' users-hosts $my_accounts

# 补全吾的脚本
#_ds()
#{
#    find "$HOME/应用/脚本" '!' -type d -and '(' -perm 755 -or -perm 777 ')' | \
#    while read line ; do
#        reply=("${reply[@]}" "${line#$HOME/应用/脚本/}")
#    done
#}

#compctl -K _ds ds
#zstyle ':completion:*:*:*:*:' 

#_update-svnpkg.bash()
#{
#    for i in $HOME/应用/编译/PKGBUILDs/* ; do
#        reply=("${reply[@]}" "${i#$HOME/应用/编译/PKGBUILDs/}")
#    done
#}
#compctl -K _update-svnpkg.bash update-svnpkg.bash

#compctl -g "$HOME/应用/脚本/??-*.* --help" ds
#zstyle ':completion:*:*:ds-打印脚本.bash:*' menu yes select
#zstyle ':completion:*:*:*:*:scripts' force-list always
#zstyle ':completion:*:scripts' command _show_scripts
user-complete()
{
    case $BUFFER in
        *"NN" )# "NN"替换为"*(oc[1])"
            BUFFER="${BUFFER%NN}*(oc[1])"
            zle end-of-line
            ;;
        '')BUFFER='cd ' # do not really like it,
                        # but hate the <TAB> when empty line much more,,,
            zle end-of-line
            ;;
    esac
    zle expand-or-complete
}
zle -N user-complete
bindkey "\t" user-complete
