#!/bin/zsh --source

#alias -g rm='RemoveFile'
#alias ls='ls -h --color=always'
eval "$(dircolors -b ~/.ls-colors)"
alias ls='ls -h --color=always -X --time-style="+[33m[[1;34m%Y,%_m,%_d (%u) [35m%H,%M,%S[0;33m][0m" --hide="*~" --hide="*-backup" --hide="*.bak"' #hide backupfiles
alias l='ls -l'
alias la='ls -A'
alias sed='sed -r'
alias make=ColorMake
alias grep='egrep'
alias egrep="GREP_COLOR=\"\$(echo 3\$[\$(date +%N)%6+1]';1;4;40')\" egrep --color=always"
alias less='less -R'
alias df='df -Th'
alias du='du -h'
alias a=awk
alias s=sed
alias p=less
#alias g=grep
alias -g showip='curl ifconfig.me' # 显示计算机外网ip
#alias irssi=Irssi-Alias
alias dsame="awk '"'!a[$0]++'"'" # 累死人。
#alias gssh='ssh -2 -p443 tusooa@shell.cjb.net ; ssh -2D7070 -p443 tusooa@shell.cjb.net'
alias updateMail='fp -v <(gpg --decrypt ~/个人/账号/mail.gpg) -f ~/.getmail/getmailrc.in -o ~/.getmail/getmailrc; fp -v <(gpg --decrypt ~/个人/账号/mail.gpg) -f ~/.msmtprc.in -o ~/.msmtprc; chmod 600 ~/.getmail/getmailrc ~/.msmtprc'
alias rm=dustbin
alias clearexe='pstree G --no-color \.exe | perl -M5.012 -pe '\''system "pkill", /\|-([A-Za-z\.]+)/'\'
# command prompt
alias \$=''
alias ●=''
alias ☎=''
alias ']'=''
alias 'tlcr:'=':' #这一行都是提示符.
alias p5='perl -M5.012'
alias onlybird='ssh -D7070 -p8888 -Nt onlybird@ssh2015.unssh.com'
alias get-contributors-list='git log --pretty=email G "^From:" | perl -e '\''while (<>) {chomp; $_{$_}++ }; print $_, ": ", $_{$_}, "\n" for sort { $_{$b} <=> $_{$a} } keys %_'\'

that()
{
    local dir="$HOME/Logs/$(date +%Y/%m/)"
    mkdir -pv "$dir"
    echo "开始。"
    arecord -f cd -t raw | lame -x -r /dev/stdin "${dir}$(date +%d,%u,%H,%M,%S)"
    echo "完成。"
}
pd()
{
    local fn="$1"
    shift
    perl -MCarp::Always -Mdiagnostics "$(which "$fn")" "$@"
}
# Aliases for todo and remind
# removed, (replaced by calendar)

# 后缀别名
alias -g A='|awk'
alias -g L='|less'
alias -g P='|perl'
alias -g G="|g"
alias -g S='|sed'
alias -g B='S "s@\x1B\[[0-9;]*[mK]@@g"'
alias -g D='|dsame'
alias -g NN="*(oc[1])" # zsh里代表当前目录下最后修改的文件的alias http://roylez.heroku.com/2010/03/06/zsh-recent-file-alias.html
#全部历史纪录 topx
topx()
{
    history 0 | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | grep -v "./" | column -c3 -s " " -t | sort -nr | nl | head -n "$1"
}

e()
{
    local NEWPATH="$(echo "$PATH" | sed -e 's@应用/脚本@Apps/Scripts@g;s@安装@Install@g;s@游戏@Games@g;')"
    if [ "$*" ] ; then
        PATH="$NEWPATH" "$@"
    else
        echo english path: "$NEWPATH"
    fi
}

#[Esc][h] man 当前命令时，显示简短说明 
alias run-help >&/dev/null && unalias run-help
autoload run-help

# Screen Aliases
#if [ "$TERM" = screen ] ; then
#    alias mutt='screen -t email mutt'
#    alias irssi='screen -t chat Irssi-Alias'
#fi

#进入相应的路径时只要 cd ~xxx
hash -d dw="$HOME/Download"
hash -d scripts="$HOME/Apps/bin"
hash -d apps="$HOME/Apps"
hash -d gcfg="$HOME/Apps/Config"
hash -d dsrc="$HOME/Download/Source"

function inList
{
    local var="$1" i
    shift
    for i in "$@" ; do
        if [[ "$var" = "$i" ]] ; then
            return 0
        fi
    done
    return 1
}

c()
{
    if [ "$*" ] ; then
        LC_ALL=C "$@"
    fi
}

