#!/bin/zsh --source

export EDITOR='emacsclient' PACKAGER='tusooa@gmail.com'
export FCDWDIR="$HOME/个人/下载/full circle"
# 输入法
export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE=fcitx GTK_IM_MODULE=fcitx
export XIM=fcitx XIM_PROGRAM=fcitx

# do not set language for ourselves
# LANG
#if [[ $TERM = linux ]] ; then
#    LANG=en_US.UTF-8
#else
#    LANG=zh_CN.UTF-8
#fi
# 解决了如下bug
# ssh -pXXX tusooa@tusooa-laptop
# 时ls显问号的问题
export LANG
# less
export PAGER=less
export MANPAGER='/usr/bin/less -isR'
export LESS_TERMCAP_md=$'\e[1;31m' #bold1
export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;44;33m' #search highlight
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;2;32m' #bold2
export LESS_TERMCAP_ue=$'\e[0m'
export LESS="-M -i -R --shift 5"
export LESSCHARSET=utf-8
export GROFF_NO_SGR=1 #groff不转换颜色
export READNULLCMD=less
# grep.perl color
export G_COLORS='fn=1;33:ln=1;32'
# In archlinux the pipe script is in PATH, how ever in debian it is not
[[ -x $(whence -cp src-hilite-lesspipe.sh 2>/dev/null) ]] && export LESSOPEN="| src-hilite-lesspipe.sh %s"
[ -x /usr/share/source-highlight/src-hilite-lesspipe.sh ] && export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s" || :


# Perl Brew

#export PERLBREW_ROOT="$HOME/安装/stow/perlbrew" \
#    PERLBREW_HOME="$HOME/.perlbrew"

# android ssh auto set display
if [ "$SSH_CONNECTION" ] ; then
    export DISPLAY="${SSH_CONNECTION%% *}:0"
fi
