#!/bin/zsh --source

#关于历史纪录的配置
#历史纪录条目数量
export HISTSIZE=100000
#注销后保存的历史纪录条目数量
export SAVEHIST=100000
#历史纪录文件
export HISTFILE=~/.zhistory
#以附加的方式写入历史纪录
setopt INC_APPEND_HISTORY
#如果连续输入的命令相同，历史纪录中只保留一个
setopt HIST_IGNORE_DUPS      
#为历史纪录中的命令添加时间戳      
setopt EXTENDED_HISTORY      
#启用 cd 命令的历史纪录，cd -[TAB]进入历史路径
setopt AUTO_PUSHD
#相同的历史路径只保留一个
setopt PUSHD_IGNORE_DUPS
#setopt HIST_IGNORE_SPACE      
export HISTFILE="$HOME/.zhistory"

#允许在交互模式中使用注释  例如：
#cmd #这是注释
setopt INTERACTIVE_COMMENTS      
#扩展路径
#/v/c/p/p => /var/cache/pacman/pkg
setopt complete_in_word
#禁用 core dumps
limit coredumpsize 0
#Emacs风格 键绑定
bindkey -e
#设置 [DEL]键 为向后删除
bindkey "\e[3~" delete-char
#以下字符视为单词的一部分
WORDCHARS='*?_-[]~=&;!#$%^(){}<>'
# 不显示bad pattern的信息。
unsetopt badpattern
# 自动更正命令
setopt correct
# Glob匹配失败的时候使用原来内容，不报错
setopt nonomatch

command_not_found_handler()
{
    if [ -f "$HOME/.share/programsList" ] ; then
        local l="$(grep "/${1}$" $HOME/.share/programsList)"
        if [ "$l" ]; then
            echo "packages contains the command \`$1':"
            echo "$l" | awk '{print "\033[0;1;32m" $1 "\t\t\033[31m /" $2}'
            echo "Run \`get <package>' to install it"
        fi
    fi
    return 127
}

: <<'COMMENT'
export RM_DESTDIR="$HOME/.del/"
rm()
{
    [ "$RM_DESTDIR" ] || export RM_DESTDIR="$HOME/.del/"
    mkdir -p "$RM_DESTDIR"
    while [ $# -gt 0 ]
    do
        case "$1" in 
            -*)
                shift
                ;;
            *)
                [ -z "$1" ] && continue
                case "$1" in
                    /*)file=$1;;
                    *)file=$PWD/$1;;
                esac
                i=0
                base="$(basename "$file")"
                dest="$((i++))-$base"
                while [ -e "$RM_DESTDIR$dest" ]; do
                    dest="$((i++))-$base"
                done
                mv "$file" "$RM_DESTDIR$dest"
                echo -e "$file -> $dest" >> $HOME/.rm
                shift
                ;;
        esac
    done
}
COMMENT
mkcd()
{
    mkdir -p "$1" && cd "$1"
}

