#!/bin/bash --source
# vim : ft=bash

# Svn 库
# Svn CheckHead之类的包装。

Ec_SvnError=21

svnCheckHead()
{
    # Usage : svnCheckHead <svnTrunk>
    # Output : Svn HEAD
    
    [ "$1" ] || return 1
    #rm -rf /tmp/bash/svn/co-tmp
    #mkdir -p /tmp/bash/svn/
    #pushd /tmp/bash/svn/ &> /dev/null
    #    LC_ALL=C svn -N co "$1" co-temp &> /tmp/bash/svn/co-log || return 1
    #    sed -rne 's/^.*[Rr]evision ([0-9]+).*$/\1/p' /tmp/bash/svn/co-log
    #popd &> /dev/null
    
    # From /usr/bin/makepkg 1330l:
    LC_ALL=C svn info $_svntrunk | sed -n 's/^Last Changed Rev: \([0-9]*\)$/\1/p'
}

