
* 调教和查询指令(&Scripts::Windy::Conf::userdb::reloadDB())
** 风妹当问xxx则答---
   用这个就好了，可以自动判定什么语气词啊什么表情啊，多好w【具体差别看注1】
** 风妹若问xxx即答---
   看到收到的讯息里「有」xxx就回。可能会炸。
** 风妹问xxx答---
   看到收到的讯息「正正好好」「就是」xxx就回。
** 风妹知道多少
   就是所谓的词汇量了x
** 风妹记得xxx亦是yyy
   在以后的调教中，看到<yyy>，就把xxx也包括进去。
** 风妹记得xxx也是yyy
   和上一个差不多，但是如果xxx是什么表情的话，还是用上一条吧。【具体差别看注2】
   
   撤回前言。最好别用嗯x
** 风妹什么是yyy
   自己试一下就知道了x
** 风妹重生
   就是把词库都重载一遍0 0【想知道为什么看注3】

* 然后你要知道有一个东西叫「正则表达式」
  woc为什么这名字那么奇怪啊- -兔嫂也不知道- -别管- -意思差不多就好了- -搜一下能搜到很多东西- -
  
  为了节省时间兔嫂就简单讲一下食用方法吧（喂这玩意儿不能吃啊）
  
  - -要是被那些dalao看到就尴尬了- -这可是GitHub啊
  
  - -嘛作为一篇科普文章。。。不管了（反正也没几个人fo兔嫂，星(Star)了这个repo的更是没几个了）
  
  好了废话不多说了
  
  在这个奇怪的东西里面，一般的字就是一般的意思，但是有一些符号（都是英文符号啊x）并不是本身的意思（- -能懂吗x）
  
  首先是一个.点号 意思就是「不管这里有『一个』什么东西（我们以后称作『字符』，什么叫字符呢，嘛- -理解下就好了- -兔嫂也解释不太清楚- -反正你打进去什么东西如果按『一下』删除键能删掉应该就是一个字符），不论是字啊还是符号啊还是空格啊，只要是『一个』，我都把它当一个豆豆吃掉」（果然是食用方法）
  
  然后是(xxx)括号，表示这里面的东西是要存起来之后用的（在「答」里面用【捕获x】获取，x是几就拿走第几个括号里的内容，括号的顺序按照左括号「(」计算）
  
  还有一个(?:xxx)，只是分个组而已并不能存下来，有什么用看下面
  
  「|」竖线- -姑且这么叫吧- -大约就是「或者」的意思比如「兔嫂|兔喵」就是两个里面选一个当然正常人更会用「分组」的「兔(?:嫂|喵)」
  
  「?」问号表示「前面这个可以出现『一次』也可以没有」比如「蠢?雨心(?:萝莉)?」- -分组和不分组是看只有一个字的才能不分- -
  
  「*」星号表示「出现0次以上」（mdzz好难过的说法）比如「兔兔*嫂」可以抓到「兔嫂」、「兔兔嫂」、「兔兔兔嫂」等等- -
  
  「+」加号表示「出现1次以上」于是上面那个又可以写成「兔+嫂」
  
  「{a,b}」表示至少出现a次至多出现b次然后a和b都是可以省略，a省略默认是0，b省略默认是无穷大，比如说「(?:兔嫂){1,}」
  
  「[xyz]」表示这「一个」字符既可以是x又可以是y又可以是z比如「兔[嫂喵]」和那个竖线里的例子是一样的
  
  「^」「$」分别表示行首和行尾，在调教里一般是没有必要写上的嗯
  
  「\」反斜线加在刚才提到的这些特殊符号之前，表示只要原本这个符号「\|」「\?」「\\」这样。
  
  不要问兔嫂反斜线加在一般的字前面会发生什么（太多不想讲）
*** 还是讲几个吧
    \d 一个数字（0-9）
    
    \w 一个字（不算符号）
    
    好像也没什么别的常用的了
*** 然后给几个题目 答案看注4
**** 1 找「一只兔嫂」
**** 2 找「一只兔嫂」或者「一只风妹」
**** 3 找「雨心」，前面可能有「蠢」
**** 4 找「雨心」，后面可能有「萝莉」或者「妹妹」
**** 5 找「雨心」，前面可能有「蠢」，后面可能有「萝莉」或者「妹妹」
**** 6 找「兔嫂」或者「雨心」或者「泠喑」，并且把找到的东西存下来
**** 7 找「兔嫂」或者「雨心」或者「泠喑」，如果是「泠喑」就存下来
**** 8 找「雨」后面有一个或者很多个「心」（雨心，雨心心，雨心心心，。。。）

* 方括号和尖括号是用来干什么的(Scripts::Windy::Conf::smartmatch)
** 一言以蔽之，是用来偷懒的
*** <>这个理解成同义词就好，然后定义看/config/config+Scripts/windy-conf/replacements.db
    这边拿几个比较重要的说一下0 0
    
    <风妹>表示叫风妹的（等于没解释啊）
    
    <我><你><是><没><能><以后><为什么>这些都是字面意思因为比较常用嘛而且近义词有点多就拿来偷个懒x（还是没解释啊）
    
    <d1>表示一个【
    
    <d2>表示一个】
    
    <d5>表示一个<
    
    <d6>表示一个>
    
    <换行>表示一个换行
    
    <下讯>表示拆成两条讯息发
    
    然后还有一些是不要写入问题的
    
    <前><中><后> 这些别改
    
    <叹词><句首叹词><句中叹词><句末叹词><表情><_状态_><标点>这几个是要往里面添的你觉得那一类比较合适就加进去
    
    - -还有别管什么助词语气词什么- -兔嫂觉得叹词比较好打就用了- -习惯就好- -
**** 关于<xxx〔yyy,zzz〕>这种东西啊
     用倒是可以用，但是要加的话只能手改文件比较麻烦嗯
*** 【】这个啊($Scripts::Windy::Conf::smartmatch::aliases)
    主要是对讯息作一些判定，或者是得到一些关于讯息的东西
    
    在「问」里面会作为条件，「答」里面会把结果放到答语里w
    
    看了一下东西好多啊- -挑几个重要的说吧
    
    【来讯者名】
    
    【来讯者id】
    
    【群中有xxxxx】
    
    【xxx并且yyy】
    
    【xxx或者yyy】
    
    【不是xxx】
    
    【xxx为yyy】这个是判定xxx和yyy是不是一样
    
    【概率0.0yyy】
    
    【加n好感】（也可以是负数，然而不能是小数）
    
    【加n心情】（同上）
    
    【截止】这个表示到此就不再往下搜词库了，「并且回复这一条的内容，如果没内容或者是『0』就不回复」
    
         所以会有一个很诡异的【加-10好感并且0】
         
    【捕获n】表示「问」里面第几个括号()里的东西。不算(?:)。
    
    【换行】
    
    【下讯】有这两条是因为【】里面不能用<>，如果不是在【】里面还是用<>吧。快。
    
    【xxx+yyy】用来分割，或者连接
    
    比如说【来讯者名+早】，【不+是xxxx】，【大约可能或+者也许】
    
    如果要出现一个加号的话双写就好了【比如说++这样】
    
    【好感判：a,b,c,d】
    
    【心情判：a,b,c,d】如果哪一条留空或者「是0」就用「后面那个」
    
    比如说【好感判：w,- -,,。】【好感判：概率0.3加4好感并且0,qwq,,。】
**** 题目 这个写的会比较抽象一点x 答案看注解5
***** 1 对别人说「xxx早」（用\w）进行应和（回「xxx早」）并且根据心情加上语气词（w,- -,。,。）
***** 2 一个复述功能（喵 复述）
***** 3 「还有xxx分钟」（用\d）根据好感回答（真的还有xxx分钟喵w？,是嘛- -,哦。,。。）
***** 4 对氿潆的词汇量进行赞赏（不需要根据好感）
***** 5 叫风妹的时候回复两条 第一条「何事」，根据好感(w？,- -,。,。)第二条「西风不待人」，根据心情(wxxx,x,。,。)


* 注解
** 1
   当问xxx则答 相当于 若问^<前>xxx<后>$即答
   问xxx答 相当于 若问^xxx$即答
** 2
   「亦是」会给特殊符加上「\」因此对于表情一类非常有用
** 3
   就是刷新对<>里的东西的记忆嗯x
** 4 答案（在调教的时候是不需要加引号的）
*** 1 「一只兔嫂」
*** 2 「一只(?:兔嫂|风妹)」
*** 3 「蠢?雨心」
*** 4 「雨心(?:萝莉|妹妹)?」
*** 5 「蠢?雨心(?:萝莉|妹妹)?」
*** 6 「(兔嫂|雨心|泠喑)」
*** 7 「兔嫂|雨心|(泠喑)」
*** 8 「雨心+」
** 5 第二个答案
*** 1 风妹呐 当问(\w+早)则答【捕获1】【心情判：w,- -,,。】
*** 2 风妹呐 问喵 复述(.+)答【捕获1】
*** 3 风妹呐 当问还有(\d+)分钟则答【好感判：真的还有xxx分钟喵w？,是嘛- -,哦。,。。】
*** 4 风妹呐 问【来讯者id为xxxxx（这里兔嫂就不写出来了保护隐私）】咿呀~本少已经学会惹(\d+)条知识了呐，本少厉害趴~酷爱来夸奖一下啦~答【捕获1】w<下讯>妹妹好棒ww
*** 5 风妹呐 当问<风妹>则答何事【好感判：w？,- -,,。】<下讯>西风不待人【心情判：wxxx,x,,。】
